# Site settings
title:          Xem Phim Online
description:    "Xem phim Online mới miễn phí nhanh chất lượng cao. Xem phim online, phim Việt HD. Xem phim Việt Nam chiếu rạp nhanh online chất lượng cao."
baseurl:        "/"
url:            "https://jkuibap.github.io"

# Author
author:
  name:         jkuibap
  email:        jkuibap@yahoo.com

# Build settings
markdown:       kramdown

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

# Permalinks
permalink:      /:title.html
paginate:       18
paginate_path: "/page-:num/"

# Google Analytics
ga-lite: UA-133437491-1


